# Generated by Django 2.2 on 2021-03-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_remove_doctor_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionsSearched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsName', models.TextField()),
                ('numSearched', models.IntegerField(default=0)),
                ('timeFirstSearched', models.DateTimeField(auto_now_add=True)),
                ('timeLastSearched', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Department')),
            ],
        ),
    ]
