# Generated by Django 2.1.15 on 2021-03-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key_word', models.CharField(max_length=16)),
                ('link', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='questionssearched',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Department', verbose_name='科室'),
        ),
        migrations.AlterField(
            model_name='questionssearched',
            name='numSearched',
            field=models.IntegerField(default=0, verbose_name='次数'),
        ),
        migrations.AlterField(
            model_name='questionssearched',
            name='questionsName',
            field=models.TextField(verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='questionssearched',
            name='timeFirstSearched',
            field=models.DateTimeField(auto_now_add=True, verbose_name='第一次被查询'),
        ),
        migrations.AlterField(
            model_name='questionssearched',
            name='timeLastSearched',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次被查询'),
        ),
    ]
