# Generated by Django 2.2 on 2021-02-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210217_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departement',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Departement_name',
            new_name='Department_name',
        ),
    ]
