# Generated by Django 2.2 on 2021-02-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210217_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doc_id',
            new_name='Patient_id',
        ),
    ]
