# Generated by Django 2.2 on 2021-03-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210217_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_id',
        ),
    ]
