# Generated by Django 2.2 on 2021-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTest', '0002_t_result_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(default='result_id', max_length=160, verbose_name='结果编号字典')),
                ('patient_id', models.CharField(default='patient_id', max_length=160, verbose_name='患者编号字典')),
                ('result_comment', models.CharField(default='result_comment', max_length=160, verbose_name='患者状况字典')),
                ('enabled', models.CharField(default='enabled', max_length=160, verbose_name='有效字典')),
                ('deleted', models.CharField(default='deleted', max_length=160, verbose_name='无效字典')),
                ('created_time', models.CharField(default='created_time', max_length=160, verbose_name='入院时间字典')),
                ('updated_time', models.CharField(default='updated_time', max_length=160, verbose_name='出院时间字典')),
                ('treatment_id', models.CharField(default='treatment_id', max_length=160, verbose_name='诊疗方法编号字典')),
                ('treatment_name', models.CharField(default='treatment_name', max_length=160, verbose_name='诊疗方法字典')),
                ('comment', models.CharField(default='comment', max_length=160, verbose_name='诊疗评论字典')),
                ('illness_id', models.CharField(default='illness_id', max_length=160, verbose_name='疾病编号字典')),
                ('illness_name', models.CharField(default='illness_name', max_length=160, verbose_name='疾病名字典')),
                ('blood_sugar', models.CharField(default='blood_sugar', max_length=160, verbose_name='患者血糖字典')),
                ('blood_pressure', models.CharField(default='blood_pressure', max_length=160, verbose_name='患者血压字典')),
                ('blood_fat', models.CharField(default='blood_fat', max_length=160, verbose_name='患者血脂字典')),
                ('department_id', models.CharField(default='department_id', max_length=160, verbose_name='科室编号字典')),
                ('department_name', models.CharField(default='department_name', max_length=160, verbose_name='科室名字典')),
                ('department_address', models.CharField(default='department_address', max_length=160, verbose_name='科室地址字典')),
                ('patient_name', models.CharField(default='patient_name', max_length=160, verbose_name='患者姓名字典')),
                ('gender', models.CharField(default='gender', max_length=160, verbose_name='性别字典')),
                ('birth', models.CharField(default='birth', max_length=160, verbose_name='生日字典')),
                ('age', models.CharField(default='age', max_length=160, verbose_name='年龄字典')),
            ],
        ),
        migrations.DeleteModel(
            name='t_result_format',
        ),
    ]
