# Generated by Django 2.2 on 2021-05-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileTest', '0003_auto_20210319_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_info_id', models.CharField(blank=True, max_length=6, null=True)),
                ('heart_rate', models.CharField(max_length=6, null=True)),
                ('weight', models.CharField(max_length=6, null=True)),
                ('step_number', models.CharField(max_length=6, null=True)),
                ('sleep_time', models.CharField(max_length=6, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
