# Generated by Django 2.2 on 2021-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTest', '0004_patient_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_information',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
