# Generated by Django 2.2 on 2021-05-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileTest', '0005_auto_20210527_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_information',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
