# Generated by Django 2.2 on 2021-05-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileTest', '0006_auto_20210527_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient_information',
            options={'ordering': ['-time']},
        ),
    ]
