# Generated by Django 2.2 on 2021-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTest', '0007_auto_20210528_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_information',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
