# Generated by Django 2.1.15 on 2021-02-08 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('department_address', models.CharField(max_length=100)),
                ('enabled', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_id', models.CharField(max_length=100)),
                ('illness_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('enabled', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('enabled', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.CharField(max_length=100)),
                ('result_comment', models.CharField(max_length=100)),
                ('enabled', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='t.patient')),
            ],
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_id', models.CharField(max_length=100)),
                ('treatment_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('enabled', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='t.patient')),
            ],
        ),
        migrations.AddField(
            model_name='illness',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='t.patient'),
        ),
        migrations.AddField(
            model_name='department',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='t.patient'),
        ),
    ]
