# Generated by Django 2.1.15 on 2021-02-08 03:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # 添加atomic
    dependencies = [
        ('t', '0002_auto_20210208_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_department',
            new_name='department',
        ),
        migrations.RenameModel(
            old_name='t_illness',
            new_name='illness',
        ),
        migrations.RenameModel(
            old_name='t_patient',
            new_name='patient',
        ),
        migrations.RenameModel(
            old_name='t_result',
            new_name='result',
        ),
        migrations.RenameModel(
            old_name='t_treatment',
            new_name='treatment',
        ),
    ]
