# Generated by Django 2.1.15 on 2021-02-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0004_auto_20210208_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='illness',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
