# Generated by Django 2.1.15 on 2021-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0005_auto_20210208_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='illness',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='result',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.AddField(
            model_name='department',
            name='patient_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='illness',
            name='patient_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='result',
            name='patient_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
