# Generated by Django 2.2 on 2021-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0006_auto_20210308_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='blood_fat',
            field=models.CharField(default=0, max_length=100, verbose_name='患者血脂'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illness',
            name='blood_pressure',
            field=models.CharField(default=0, max_length=100, verbose_name='患者血压'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illness',
            name='blood_sugar',
            field=models.CharField(default=0, max_length=100, verbose_name='患者血糖'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='无效'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_address',
            field=models.CharField(max_length=100, verbose_name='科室地址'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=100, verbose_name='科室编号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, verbose_name='科室名'),
        ),
        migrations.AlterField(
            model_name='department',
            name='enabled',
            field=models.IntegerField(default=0, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='department',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, verbose_name='患者编号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出院时间'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='状况'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='无效'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='enabled',
            field=models.IntegerField(default=0, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='illness_id',
            field=models.CharField(max_length=100, verbose_name='疾病编号'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='illness_name',
            field=models.CharField(max_length=100, verbose_name='疾病名'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, verbose_name='患者编号'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出院时间'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.CharField(max_length=100, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='无效'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enabled',
            field=models.IntegerField(default=0, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=100, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=100, verbose_name='患者编号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='患者姓名'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出院时间'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_time',
            field=models.DateTimeField(verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='result',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='无效'),
        ),
        migrations.AlterField(
            model_name='result',
            name='enabled',
            field=models.IntegerField(default=0, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='result',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, verbose_name='患者编号'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_comment',
            field=models.CharField(max_length=100, verbose_name='患者状况'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.CharField(max_length=100, verbose_name='结果编号'),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_time',
            field=models.DateTimeField(verbose_name='出院时间'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='诊疗评论'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入院时间'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='deleted',
            field=models.IntegerField(default=0, verbose_name='无效'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='enabled',
            field=models.IntegerField(default=0, verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, verbose_name='患者编号'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_id',
            field=models.CharField(max_length=100, verbose_name='诊疗方法编号'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(max_length=100, verbose_name='诊疗方法'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='出院时间'),
        ),
    ]
